import AddUser from '@/Components/AddUser'
import DisplayUsers from '@/Components/DisplayUsers'
import Head from 'next/head'

export default function Home() {
  return <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div className="container">
      <div className="add-user">
        <AddUser />
      </div>
      <div className="display-user">
        <DisplayUsers />
      </div>
    </div>
  </>;
}
